# Generated by Django 5.2.4 on 2025-07-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Statistic label (e.g., 'Active Farmers')", max_length=100)),
                ('value', models.CharField(help_text="Statistic value (e.g., '500+', '25')", max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-people', 'bi-geo-alt')", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional description or additional context', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Display on homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('bot', 'Board of Trustees'), ('exco', 'Executive Committee'), ('staff', 'Staff'), ('advisory', 'Advisory Board'), ('regional', 'Regional Coordinators')], default='staff', help_text='Team category for grouping', max_length=20),
        ),
    ]
