# Generated by Django 5.2.4 on 2025-07-18 02:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_statistic_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Full article content with rich text formatting'),
        ),
    ]
