# Generated by Django 5.2.4 on 2025-07-18 04:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_newsarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Full article content with rich text formatting'),
        ),
    ]
