# Generated by Django 5.2.4 on 2025-12-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_newsarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='CTA heading', max_length=200)),
                ('description', models.TextField(help_text='CTA description text')),
                ('button_1_text', models.CharField(help_text='First button text', max_length=50)),
                ('button_1_url', models.CharField(help_text='First button URL', max_length=200)),
                ('button_1_icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('button_2_text', models.CharField(blank=True, help_text='Second button text', max_length=50)),
                ('button_2_url', models.CharField(blank=True, help_text='Second button URL', max_length=200)),
                ('button_2_icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('background_style', models.CharField(default='background: linear-gradient(135deg, var(--primary-accent), var(--dark-accent));', help_text='CSS background style', max_length=200)),
                ('placement', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('programs', 'Programs Page'), ('news', 'News Detail'), ('page', 'Page Detail'), ('partners', 'Partners Page'), ('all', 'All Pages')], default='all', help_text='Where to display this CTA', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call to Action',
                'verbose_name_plural': 'Call to Actions',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main slide title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Slide subtitle', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Slide description text')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the slide', null=True, upload_to='hero_slides/')),
                ('background_color', models.CharField(default='linear-gradient(135deg, #1C4523 0%, #4CAF50 100%)', help_text='CSS background color or gradient', max_length=50)),
                ('button_1_text', models.CharField(blank=True, help_text='First button text', max_length=50)),
                ('button_1_url', models.CharField(blank=True, help_text='First button URL', max_length=200)),
                ('button_1_icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('button_2_text', models.CharField(blank=True, help_text='Second button text', max_length=50)),
                ('button_2_url', models.CharField(blank=True, help_text='Second button URL', max_length=200)),
                ('button_2_icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Slide order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_content', models.TextField(default="To promote and scale the use of AKILIMO's evidence-based agronomic advisory services across Nigeria.", help_text='Mission statement content')),
                ('mission_icon', models.CharField(default='bi-crosshair', help_text='Bootstrap icon class for mission', max_length=50)),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_content', models.TextField(default='A thriving agricultural sector in Nigeria where every smallholder farmer has access to data-driven decision support tools.', help_text='Vision statement content')),
                ('vision_icon', models.CharField(default='bi-lightbulb', help_text='Bootstrap icon class for vision', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission & Vision',
                'verbose_name_plural': 'Mission & Vision',
            },
        ),
        migrations.CreateModel(
            name='OperationalPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Pillar title', max_length=100)),
                ('description', models.TextField(help_text='Pillar description')),
                ('icon', models.CharField(help_text="Bootstrap icon class (e.g., 'bi-clipboard-data')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operational Pillar',
                'verbose_name_plural': 'Operational Pillars',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_section', models.CharField(choices=[('home_hero', 'Home - Hero Section'), ('home_about', 'Home - About Section'), ('about_hero', 'About - Hero Section'), ('about_highlights', 'About - Key Highlights'), ('about_org_structure', 'About - Organizational Structure'), ('programs_hero', 'Programs - Hero Section'), ('programs_platform', 'Programs - Platform Description'), ('partners_hero', 'Partners - Hero Section')], help_text='Page section identifier', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text='Section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Section subtitle', max_length=300)),
                ('content', models.TextField(blank=True, help_text='Section content')),
                ('badge_text', models.CharField(blank=True, help_text='Badge or label text', max_length=100)),
                ('highlight_1', models.CharField(blank=True, max_length=100)),
                ('highlight_2', models.CharField(blank=True, max_length=100)),
                ('highlight_3', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
        migrations.CreateModel(
            name='PlatformFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Feature title', max_length=100)),
                ('description', models.TextField(help_text='Feature description')),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-check-circle-fill')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Feature',
                'verbose_name_plural': 'Platform Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Team name (e.g., 'CONTENT Team')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief team description')),
                ('icon', models.CharField(help_text="Bootstrap icon class (e.g., 'bi-file-text')", max_length=50)),
                ('responsibilities', models.TextField(blank=True, help_text='Team responsibilities (one per line)')),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Team',
                'verbose_name_plural': 'Support Teams',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Program title', max_length=100)),
                ('description', models.TextField(help_text='Program description')),
                ('icon', models.CharField(help_text="Bootstrap icon class (e.g., 'bi-people-fill')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['order'],
            },
        ),
    ]
