# Generated by Django 5.2.4 on 2025-12-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_calltoaction_heroslide_missionvision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bypass_payment_requirements',
            field=models.BooleanField(default=True, help_text='When enabled, users can register and access the dashboard without payment. Disable to enforce payment requirements.', verbose_name='Bypass Payment Requirements'),
        ),
    ]
