# Generated by Django 5.2.4 on 2025-12-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_sitesettings_bypass_payment_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(default='All rights reserved.', help_text="Copyright text (year will be added automatically). Example: 'All rights reserved.'", max_length=200, verbose_name='Footer Copyright Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(default='Built with love for Nigerian Farmers', help_text="Tagline shown in footer. Example: 'Built with love for Nigerian Farmers' or 'Made with Love for Farmers'", max_length=200, verbose_name='Footer Tagline'),
        ),
    ]
