# Generated by Django 5.2.4 on 2026-08-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_sitesettings_registration_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('threads', 'Threads'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(help_text='Full link to the account, e.g. https://facebook.com/akilimonigeria')),
                ('handle', models.CharField(blank=True, help_text='Public handle without the @, e.g. akilimonigeria', max_length=100)),
                ('custom_icon', models.CharField(blank=True, help_text="Optional Bootstrap Icons class to override the default, e.g. 'bi-globe'", max_length=50)),
                ('show_in_header', models.BooleanField(default=True, help_text='Show this icon in the site header')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Show this icon in the site footer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(help_text='Post text, or a short summary of it')),
                ('image', models.ImageField(blank=True, help_text="Screenshot or the post's own image. Used when no embed code is given.", null=True, upload_to='social/')),
                ('embed_code', models.TextField(blank=True, help_text="Optional. Paste the platform's embed HTML (X → 'Embed post', Instagram → 'Embed'). Overrides the image when present.")),
                ('post_url', models.URLField(blank=True, help_text='Link to the original post')),
                ('posted_at', models.DateTimeField(blank=True, help_text='When the post went out (used for ordering and the shown date)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this post in the feed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_link', models.ForeignKey(blank=True, help_text='Which account this post came from (drives the platform badge)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='website.socialmedialink')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['order', '-posted_at', '-created_at'],
            },
        ),
    ]
