# Generated by Django 5.2.4 on 2025-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkilimoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(help_text='ID from EiA MELIA API', unique=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('usecase', models.CharField(default='AKILIMO', max_length=50)),
                ('usecase_ref_id', models.CharField(blank=True, max_length=50, null=True)),
                ('usecase_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_year', models.IntegerField(blank=True, null=True)),
                ('event_month', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_format', models.CharField(blank=True, max_length=50, null=True)),
                ('event_city', models.CharField(blank=True, max_length=200, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=500, null=True)),
                ('event_geopoint', models.CharField(blank=True, help_text='GPS coordinates', max_length=100, null=True)),
                ('farmer_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('farmer_age', models.CharField(blank=True, max_length=10, null=True)),
                ('age_category', models.CharField(blank=True, max_length=20, null=True)),
                ('farmer_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('farmer_own_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('farmer_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('farmer_position', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('participants_type', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_level1', models.CharField(blank=True, help_text='State/Region', max_length=100, null=True)),
                ('admin_level2', models.CharField(blank=True, help_text='LGA/District', max_length=100, null=True)),
                ('partner', models.CharField(blank=True, max_length=100, null=True)),
                ('org_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('org_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('org_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('crop', models.CharField(blank=True, max_length=50, null=True)),
                ('thematic_area', models.TextField(blank=True, null=True)),
                ('thematic_area_overall', models.TextField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_submitted_on', models.DateTimeField(blank=True, null=True)),
                ('api_created_on', models.DateTimeField(blank=True, help_text='Created timestamp from API', null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Complete raw data from API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='participantrecord',
            name='dashboard_p_usecase_7daed7_idx',
        ),
        migrations.RemoveIndex(
            model_name='participantrecord',
            name='dashboard_p_trainin_a6d125_idx',
        ),
        migrations.RemoveIndex(
            model_name='participantrecord',
            name='dashboard_p_gender_380a6a_idx',
        ),
        migrations.AlterField(
            model_name='datasynclog',
            name='sync_type',
            field=models.CharField(default='akilimo_participants', max_length=50),
        ),
        migrations.AddIndex(
            model_name='akilimoparticipant',
            index=models.Index(fields=['country', 'admin_level1'], name='dashboard_a_country_bcc383_idx'),
        ),
        migrations.AddIndex(
            model_name='akilimoparticipant',
            index=models.Index(fields=['event_date'], name='dashboard_a_event_d_7ee352_idx'),
        ),
        migrations.AddIndex(
            model_name='akilimoparticipant',
            index=models.Index(fields=['farmer_gender'], name='dashboard_a_farmer__57a23d_idx'),
        ),
        migrations.AddIndex(
            model_name='akilimoparticipant',
            index=models.Index(fields=['partner'], name='dashboard_a_partner_3bc943_idx'),
        ),
        migrations.AddIndex(
            model_name='akilimoparticipant',
            index=models.Index(fields=['event_type'], name='dashboard_a_event_t_c5ce1f_idx'),
        ),
        migrations.AddIndex(
            model_name='akilimoparticipant',
            index=models.Index(fields=['age_category'], name='dashboard_a_age_cat_5ea432_idx'),
        ),
    ]
