# Generated by Django 5.2.4 on 2025-07-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_partnerorganization_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Partner organization name from registration', max_length=200),
        ),
    ]
