# Generated by Django 5.2.4 on 2025-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_membership_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual Membership'), ('organization', 'Partner Organization Membership')], default='basic', max_length=20),
        ),
    ]
