# Generated by Django 5.2.4 on 2025-07-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for ID card', null=True, upload_to='profiles/'),
        ),
    ]
