# Generated by Django 5.2.4 on 2025-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='feature_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in featured partners section (0=not featured)'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display on homepage as featured partner'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner organization logo', null=True, upload_to='partner_logos/'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='success_story',
            field=models.TextField(blank=True, help_text='Success story or achievement highlight'),
        ),
    ]
