# Generated by Django 5.2.4 on 2025-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_partner_branding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('individual', 'Individual Membership'), ('organization', 'Partner Organization Membership')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Naira', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Pricing',
                'verbose_name_plural': 'Membership Pricing',
            },
        ),
    ]
