# Generated by Django 5.2.4 on 2025-11-18 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_fix_admin_log_encoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the organization was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status of the organization', max_length=20),
        ),
    ]
