# Generated by Django 5.2.4 on 2025-11-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_partner_approval_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershippricing',
            options={'ordering': ['payment_type', 'membership_type'], 'verbose_name': 'Membership Pricing', 'verbose_name_plural': 'Membership Pricing'},
        ),
        migrations.AddField(
            model_name='membership',
            name='access_suspended',
            field=models.BooleanField(default=False, help_text='Is access temporarily suspended?'),
        ),
        migrations.AddField(
            model_name='membership',
            name='access_suspended_reason',
            field=models.TextField(blank=True, help_text='Reason for access suspension'),
        ),
        migrations.AddField(
            model_name='membership',
            name='annual_dues_paid_for_year',
            field=models.IntegerField(blank=True, help_text='Year for which annual dues were last paid', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_download_certificate',
            field=models.BooleanField(default=False, help_text='Can download membership certificate'),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_download_id_card',
            field=models.BooleanField(default=False, help_text='Can download membership ID card'),
        ),
        migrations.AddField(
            model_name='membership',
            name='has_platform_access',
            field=models.BooleanField(default=False, help_text='Can access dashboard and platform features'),
        ),
        migrations.AddField(
            model_name='membership',
            name='last_annual_dues_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='registration_paid',
            field=models.BooleanField(default=False, help_text='Has the registration fee been paid?'),
        ),
        migrations.AddField(
            model_name='membership',
            name='registration_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='End of current subscription period (Dec 31)', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='Start of current subscription period (Jan 1)', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_year',
            field=models.IntegerField(blank=True, help_text='Current subscription year (e.g., 2025)', null=True),
        ),
        migrations.AddField(
            model_name='membershippricing',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information about this pricing tier'),
        ),
        migrations.AddField(
            model_name='membershippricing',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'New Registration Fee'), ('annual_dues', 'Annual Membership Dues')], default='registration', help_text='Type of payment: registration fee or annual dues', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('registration', 'New Registration Fee'), ('annual_dues', 'Annual Membership Dues')], default='registration', help_text='Purpose of this payment', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_year',
            field=models.IntegerField(blank=True, help_text='Year for which annual dues are being paid (for annual_dues payments)', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual Membership'), ('organization', 'Partner Organization Membership')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershippricing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this pricing tier currently active?'),
        ),
        migrations.AlterField(
            model_name='membershippricing',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual Membership'), ('organization', 'Partner Organization Membership')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='membershippricing',
            unique_together={('membership_type', 'payment_type')},
        ),
    ]
