# Generated by Django 5.2.4 on 2025-11-18 12:38

from django.db import migrations
from decimal import Decimal


def add_initial_pricing(apps, schema_editor):
    """Add initial pricing data for registration and annual dues"""
    MembershipPricing = apps.get_model('dashboard', 'MembershipPricing')

    # Create pricing records
    pricing_data = [
        {
            'membership_type': 'individual',
            'payment_type': 'registration',
            'price': Decimal('10000.00'),
            'description': 'One-time registration fee for individual members',
            'is_active': True
        },
        {
            'membership_type': 'organization',
            'payment_type': 'registration',
            'price': Decimal('50000.00'),
            'description': 'One-time registration fee for partner organizations',
            'is_active': True
        },
        {
            'membership_type': 'individual',
            'payment_type': 'annual_dues',
            'price': Decimal('20000.00'),
            'description': 'Annual membership dues (Jan 1 - Dec 31) - required for full platform access',
            'is_active': True
        },
    ]

    for data in pricing_data:
        MembershipPricing.objects.get_or_create(
            membership_type=data['membership_type'],
            payment_type=data['payment_type'],
            defaults={
                'price': data['price'],
                'description': data['description'],
                'is_active': data['is_active']
            }
        )


def remove_initial_pricing(apps, schema_editor):
    """Remove initial pricing data"""
    MembershipPricing = apps.get_model('dashboard', 'MembershipPricing')

    # Remove the pricing records we created
    MembershipPricing.objects.filter(
        membership_type__in=['individual', 'organization'],
        payment_type__in=['registration', 'annual_dues']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_membership_payment_system'),
    ]

    operations = [
        migrations.RunPython(add_initial_pricing, remove_initial_pricing),
    ]
