# Generated by Django 5.2.4 on 2026-04-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_initial_pricing_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANANigeriaPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='NG', max_length=10)),
                ('organization', models.CharField(max_length=300, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('is_fertilizer_company', models.BooleanField(default=False)),
                ('is_agrochemical_supplier', models.BooleanField(default=False)),
                ('is_seed_dealer', models.BooleanField(default=False)),
                ('is_ngo', models.BooleanField(default=False)),
                ('is_private_extension', models.BooleanField(default=False)),
                ('is_national_extension_govt', models.BooleanField(default=False)),
                ('is_farmer_association', models.BooleanField(default=False)),
                ('is_aggregator_buyer', models.BooleanField(default=False)),
                ('is_industrial_flour_mill', models.BooleanField(default=False)),
                ('is_starch_factory', models.BooleanField(default=False)),
                ('is_local_processing_enterprise', models.BooleanField(default=False)),
                ('is_social_enterprise', models.BooleanField(default=False)),
                ('is_govt_advisory_service', models.BooleanField(default=False)),
                ('is_microcredit_institution', models.BooleanField(default=False)),
                ('is_bank', models.BooleanField(default=False)),
                ('is_cooperative_lending', models.BooleanField(default=False)),
                ('is_research_institute', models.BooleanField(default=False)),
                ('is_university', models.BooleanField(default=False)),
                ('is_uploading_data', models.BooleanField(default=False, help_text='Partner is actively uploading data to the AKILIMO platform')),
                ('is_integrated_akilimo', models.BooleanField(default=False, help_text='Partner has fully integrated the AKILIMO advisory service')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_organization', models.OneToOneField(blank=True, help_text='Linked PartnerOrganization record (auto-matched by name)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ana_nigeria_partner', to='dashboard.partnerorganization')),
            ],
            options={
                'verbose_name': 'ANA Nigeria Partner',
                'verbose_name_plural': 'ANA Nigeria Partners',
                'ordering': ['organization'],
            },
        ),
    ]
