# Generated by Django 5.2.4 on 2026-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_ana_nigeria_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akilimoparticipant',
            name='event_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
