# Generated by Django 5.2.4 on 2026-07-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_increase_event_city_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User dashboard preferences'),
        ),
    ]
