# Generated by Django 5.2.4 on 2026-08-31 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_partner_slugs(apps, schema_editor):
    """
    Give every existing partner a unique slug before the unique constraint
    lands — otherwise they would all share an empty slug and collide.
    """
    from django.utils.text import slugify

    PartnerOrganization = apps.get_model('dashboard', 'PartnerOrganization')
    seen = set()

    for partner in PartnerOrganization.objects.all().order_by('pk'):
        base = slugify(partner.name)[:200] or slugify(partner.code) or f'partner-{partner.pk}'
        slug, n = base, 2
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen.add(slug)
        partner.slug = slug
        partner.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_membership_free_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='about',
            field=models.TextField(blank=True, help_text='Full description of the organization shown on its public page'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='areas_of_work',
            field=models.TextField(blank=True, help_text="One area of work per line, e.g. 'Cassava agronomy'"),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Wide banner image for the public partner page', null=True, upload_to='partners/covers/'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='has_public_page',
            field=models.BooleanField(default=True, help_text="Show this organization's own page on the public website"),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='mission',
            field=models.TextField(blank=True, help_text='Mission statement'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='URL for the public partner page (auto-generated from the name)', max_length=220),
        ),
        migrations.RunPython(populate_partner_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partnerorganization',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL for the public partner page (auto-generated from the name)', max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_partner_admin',
            field=models.BooleanField(default=False, help_text="Can edit this partner organization's public page (about, services, gallery)."),
        ),
        migrations.CreateModel(
            name='PartnerGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('taken_on', models.DateField(blank=True, help_text='When the photo was taken', null=True)),
                ('location', models.CharField(blank=True, help_text='Where the work took place', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='dashboard.partnerorganization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_gallery_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Gallery Image',
                'verbose_name_plural': 'Partner Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap Icons class, e.g. 'bi-tree' (optional)", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dashboard.partnerorganization')),
            ],
            options={
                'verbose_name': 'Partner Service',
                'verbose_name_plural': 'Partner Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
