# Generated by Django 5.2.4 on 2026-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_add_content_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Pay Online (Paystack)'), ('manual', 'Bank Transfer')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('X4L', 'X4L')], max_length=5),
        ),
    ]
