# Generated by Django 5.2.4 on 2026-06-02 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_add_payment_method_and_tshirt_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Booth, Premium Booth', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price in Naira', max_digits=10)),
                ('perks', models.TextField(blank=True, help_text="What's included — one item per line")),
                ('max_slots', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor_packages', to='conference.conference')),
            ],
            options={
                'verbose_name': 'Exhibitor Package',
                'verbose_name_plural': 'Exhibitor Packages',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Company / Organization')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='conference/exhibitors/logos/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('paystack', 'Pay Online (Paystack)'), ('manual', 'Bank Transfer')], default='paystack', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled'), ('waived', 'Fee Waived')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='conference.conference')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibitors', to='conference.exhibitorpackage')),
            ],
            options={
                'verbose_name': 'Exhibitor',
                'verbose_name_plural': 'Exhibitors',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitorShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price in Naira (optional)', max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='conference/exhibitors/')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before public display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='conference.exhibitor')),
            ],
            options={
                'verbose_name': 'Exhibitor Showcase Item',
                'verbose_name_plural': 'Exhibitor Showcase Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LOCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text="Role on the committee, e.g. 'Chairperson'", max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_members', to='conference.conference')),
            ],
            options={
                'verbose_name': 'LOC Member',
                'verbose_name_plural': 'LOC Members',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
