# Generated by Django 5.2.4 on 2026-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_exhibitorpackage_exhibitor_exhibitorshowcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the payment receipt and welcome email have been sent'),
        ),
    ]
