# Generated by Django 5.2.4 on 2026-06-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_registration_confirmation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='receipt_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the payment receipt email specifically has been sent'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the full confirmation (receipt + welcome) has been sent'),
        ),
    ]
