# Generated by Django 5.2.4 on 2026-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_registration_receipt_email_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='For your own reference', max_length=200)),
                ('email', models.EmailField(help_text='The link is sent here, and only this inbox can sign in', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to immediately revoke access')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Verifier',
                'verbose_name_plural': 'Payment Verifiers',
                'ordering': ['name', 'email'],
            },
        ),
    ]
