# Generated by Django 5.2.4 on 2026-07-03 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_paymentverifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='sponsor_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_sponsor',
            field=models.BooleanField(default=False, help_text='Complimentary sponsor registration — captured via the private sponsor link, with no fee charged.'),
        ),
    ]
