# Generated by Django 5.2.4 on 2026-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_rename_sponsor_to_stakeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='For your own reference', max_length=200)),
                ('email', models.EmailField(help_text='The access link is sent here, and only this inbox can sign in', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to immediately revoke access')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('link_sent_at', models.DateTimeField(blank=True, help_text='When the most recent access link was emailed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abstract Reviewer',
                'verbose_name_plural': 'Abstract Reviewers',
                'ordering': ['name', 'email'],
            },
        ),
    ]
