# Generated by Django 5.2.4 on 2026-08-31 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_abstractreviewer_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account name shown for bank transfers', max_length=200),
        ),
        migrations.AddField(
            model_name='conference',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='conference',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. Sterling Bank', max_length=120),
        ),
        migrations.AddField(
            model_name='conference',
            name='sponsorship_contact_email',
            field=models.EmailField(blank=True, help_text='Where sponsorship and exhibition enquiries should go', max_length=254),
        ),
        migrations.AddField(
            model_name='exhibitorpackage',
            name='space_structure',
            field=models.CharField(blank=True, help_text="Booth size and structure, e.g. '2m x 2m booth; 2m x 2m backwall with demarcation sides'", max_length=300),
        ),
        migrations.CreateModel(
            name='SponsorshipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Speaking Opportunity', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Optional clarification shown under the row label', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Row order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_benefits', to='conference.conference')),
            ],
            options={
                'verbose_name': 'Sponsorship Benefit (table row)',
                'verbose_name_plural': 'Sponsorship Benefits (table rows)',
                'ordering': ['order', 'label'],
                'unique_together': {('conference', 'label')},
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Diamond, Platinum, Gold', max_length=100)),
                ('position', models.CharField(blank=True, help_text="Sponsorship position, e.g. 'Exclusive Conference Presented By'", max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in Naira. Leave blank when the tier is a range - use Price display instead.', max_digits=12, null=True)),
                ('price_display', models.CharField(blank=True, help_text="Overrides the formatted price, for ranges such as 'NGN 50,000 - NGN 500,000'", max_length=100)),
                ('accent_color', models.CharField(blank=True, default='', help_text='Hex colour for the column header, e.g. #B9F2FF. Falls back to the conference green.', max_length=7)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this column as the recommended tier')),
                ('order', models.PositiveIntegerField(default=0, help_text='Column order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_packages', to='conference.conference')),
            ],
            options={
                'verbose_name': 'Sponsorship Package',
                'verbose_name_plural': 'Sponsorship Packages',
                'ordering': ['order', '-price'],
                'unique_together': {('conference', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPackageBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, help_text="What this package offers. Leave blank (or enter a dash) for 'not included'.")),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_values', to='conference.sponsorshipbenefit')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_values', to='conference.sponsorshippackage')),
            ],
            options={
                'verbose_name': 'Sponsorship Benefit Value',
                'verbose_name_plural': 'Sponsorship Benefit Values',
                'ordering': ['benefit__order'],
                'unique_together': {('package', 'benefit')},
            },
        ),
    ]
